### ISSUE TITLE
Import of the lib in ./docs fails

### ISSUE THREAD

**Issue by 271ch** [271ch/fomantic-ui-vue#1]
This repo is mainly a lib with vue components plus a vue app in the `docs` folder to test it. 

To reproduce the error:
* in the root of the repo execute `npm run buildProd` in order to generate the package
* in the ./docs folder execute `npm run serve`
* the error is `"export 'default' (imported as 'FuiVue') was not found in '../..'`
* location of the code causing the error: ./docs/src/main.js , lines 5-9

**Comment by awaisalee** [comment]
The issue is nothing but you have to add a full path for the component or file..
please try `import FuiVue from "../../src"`

You can thank me later

**Comment by iakhator** [comment]
There you go with your answer

**Comment by 271ch** [comment]
@awaisalee I noticed that in your correction, the path `../../src` points to the source of the package and not to the built package in `/dist/main.js`

**Comment by awaisalee** [comment]
@271ch You may not found custom components in your build versions, if you wanna use then you have to point it out to the main app `../../src/index.js` 

PS: build consists of the compiled code of your app
